logging:
  level:
    '[com.my]': DEBUG
spring:
  datasource:
    url: jdbc:mysql://192.168.1.3/jtsys
    username: root
    password: Mysql8@Root!
  thymeleaf:
    prefix: classpath:/templates/pages/
    suffix: .html
    cache: false
  aop:
    proxy-target-class: false #jdk
  task:
    execution:
      pool:
        core-size: 5
        max-size: 15
        queue-capacity: 100
 
mybatis:
  configuration:
    default-statement-timeout: 30
    map-underscore-to-camel-case: true
  mapper-locations:
  - classpath:/mapper/*/*.xml

server:
  port: 80
  tomcat:
    uri-encoding: utf-8
  servlet:
    context-path: /

page:
  config:
    pageSize: 10